см 1.10 верстка макета авторизации
frontend-park-mail-ru/2023_1_CashMap pull request #1
Opened 2023-03-01 15:14 UTC by BazaleevFedor

2023-03-01 21:04 UTC, DPeshkoff requested changes
я бы все-таки на классы перешел, имхо так будет лучше

2023-03-01 21:04 UTC, DPeshkoff commented on html/authorization.css
> +    color: #D9D9D9;
гоу сразу в переменные перетащим

2023-03-01 21:04 UTC, DPeshkoff commented on html/authorization.html
> +            <title-text>Авторизвция</title-text>
опечатка

2023-03-01 21:04 UTC, DPeshkoff commented on html/authorization.html
> +<html lang="en">
чую неправду, страница не en

2023-03-01 21:04 UTC, DPeshkoff commented on html/authorization.html
> +<div class="grid">
семантически это main

2023-03-01 21:04 UTC, DPeshkoff commented on html/authorization.html
> +            <input-field2>
мне сильно не нравится, что у нас еще и индексы появились
кажется, что это чересчур усложняет верстку

2023-03-02 20:08 UTC, BazaleevFedor commented on html/authorization.css
> +    color: #D9D9D9;
закинул в переменные все цвета и размеры

2023-03-02 20:08 UTC, BazaleevFedor commented on html/authorization.html
> +            <input-field2>
заменил на классы с дата атрибутом

2023-04-04 17:45 UTC, closed without merging