см 1.9 поднять веб сервер для фронта
frontend-park-mail-ru/2023_1_CashMap pull request #2
Opened 2023-03-01 18:10 UTC by BazaleevFedor

2023-03-01 21:06 UTC, DPeshkoff requested changes

2023-03-01 21:06 UTC, DPeshkoff commented on server/index.js
> +    const filepath = `./html${normalizedUrl}`;
странное ./html, на костыль похоже)

2023-03-02 10:49 UTC, BazaleevFedor commented on server/index.js
> +server.listen(SERVER_PORT);
добавил вывод

2023-03-02 10:55 UTC, BazaleevFedor commented on server/index.js
> +    const filepath = `./html${normalizedUrl}`;
вынес в константу, определяющую путь к статике. добавил возврат картинок еще.

2023-04-04 17:50 UTC, closed without merging