Cm 3.1 починить баги авторизации
frontend-park-mail-ru/2023_1_CashMap pull request #47
Opened 2023-04-19 18:27 UTC by BazaleevFedor

2023-04-21 01:37 UTC, DPeshkoff requested changes

2023-04-21 01:37 UTC, DPeshkoff commented on public/index.js
> +import imgStore from "./stores/imgStore.js"; /* НЕ УДАЛЯТЬ!!! */
А почему не удалять?

2023-04-21 01:37 UTC, DPeshkoff commented on public/views/signInView.js
> +                userStore.user.errorAuth = 'Необходимо заполнить корректно все поля';
#48

2023-04-21 18:51 UTC, BazaleevFedor commented on public/index.js
> +import imgStore from "./stores/imgStore.js"; /* НЕ УДАЛЯТЬ!!! */
т.к. колбеки сторов добавляются при вызове конструктора их классов в диспетчер, явного упоминания сторов нигде нет. поэтому если не подключить через import, конструктор не будет вызван и стора не будет с системе...

2023-04-23 19:22 UTC, DPeshkoff approved these changes

2023-04-24 11:35 UTC, ArKarina approved these changes

2023-04-24 20:56 UTC, thxtomslf approved these changes
Федя, ответь на вопросы в пр, пожаааалуйста

2023-04-25 03:35 UTC, BazaleevFedor commented on public/views/signInView.js
>      _preRender() {
рендер во всех вьюхах одинаковый, поэтому я не хотел дублировать строки и вынести его в базовый класс, из которого будут запускаться методы для конкретного класса. в пререндер я вынес отличающиеся элементы отрисовки.

2023-04-25 03:52 UTC, BazaleevFedor commented on public/components/signInPath/signInPath.css
>      align-items: center;
display по умолчанию у элемента span - inline. Но у этого элемента будет display: grid, т.к. этот параметр унаследуется от внешнего блока input-block, у которого он задан явно. не помню зачем я удалил явное указание у ошибки.

2023-04-25 15:19 UTC, thxtomslf commented on public/views/signInView.js
>      _preRender() {
лайк

2023-04-25 15:19 UTC, thxtomslf approved these changes

2023-04-25 17:53 UTC, merged