Cm 3.2 починить баги регистрации
frontend-park-mail-ru/2023_1_CashMap pull request #48
Opened 2023-04-19 18:28 UTC by BazaleevFedor

2023-04-21 01:35 UTC, DPeshkoff requested changes

2023-04-21 01:35 UTC, DPeshkoff commented on public/components/signUpPath/signUpPath.handlebars
> +            <a class="input-table__link font-MailSansRoman font-size-16 font-color-info cursor-pointe" id="{{ link.jsId }}"> {{ link.text }} </a>
```suggestion
            <a class="input-table__link font-MailSansRoman font-size-16 font-color-info cursor-pointer" id="{{ link.jsId }}"> {{ link.text }} </a>
```

2023-04-21 01:35 UTC, DPeshkoff commented on public/modules/validation.js
> +				error: `Пароль должен быть длинее ${MIN_PASSWORD_LENGTH} символов`
```suggestion
				error: `Пароль должен быть длиннее ${MIN_PASSWORD_LENGTH} символов`
```

2023-04-21 01:35 UTC, DPeshkoff commented on public/modules/validation.js
> +				error: `Пароль должен быть длинее ${MIN_PASSWORD_LENGTH} символов`
```suggestion
				error: `Пароль должен быть длиннее ${MIN_PASSWORD_LENGTH} символов`
```

2023-04-21 01:35 UTC, DPeshkoff commented on public/views/signUpView.js
> +                userStore.user.errorReg = 'Необходимо заполнить корректно все поля';
Мне кажется, тут лучше без "необходимо", да и не очень ясно, что такое "корректно"

```suggestion
                userStore.user.errorReg = 'Заполните все указанные поля';
```

Если хочется корректно, то лучше

```suggestion
                userStore.user.errorReg = 'Заполните корректно все поля';
```

![изображение](https://user-images.githubusercontent.com/31134795/233519896-7ff9f6d5-478b-4390-a640-73a85d46066e.png)

2023-04-23 19:21 UTC, DPeshkoff approved these changes

2023-04-24 11:38 UTC, ArKarina approved these changes

2023-04-24 21:28 UTC, thxtomslf approved these changes

2023-04-25 09:20 UTC, merged