Cm 3.5 починить добавления в друзья
frontend-park-mail-ru/2023_1_CashMap pull request #49
Opened 2023-04-21 21:14 UTC by ArKarina

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/102531036/233735759-9d939b51-63b4-423c-87b2-e5ddc7856ba8.png">

2023-04-23 19:06 UTC, DPeshkoff requested changes

2023-04-23 19:06 UTC, DPeshkoff commented on public/components/friend/friend.css
> +    background-color: var(--background-color-menu);
А фоллбеки?

2023-04-23 19:06 UTC, DPeshkoff commented on public/stores/friendsStore.js
> +                friend.isUser = true;
не ясно - бывает друг и не пользователь?

2023-04-23 19:06 UTC, DPeshkoff commented on public/views/friendsView.js
> +		for (let i = 0; i < this._unsubUser.length; i++) {
forEach, every?

2023-04-24 19:03 UTC, BazaleevFedor approved these changes

2023-04-24 19:05 UTC, BazaleevFedor requested changes

2023-04-24 19:05 UTC, BazaleevFedor commented on public/components/friend/friend.css
> +    cursor: pointer;
я вроде создавал отдельный класс (cursor-pointer), можно подключить его в hendlebars

2023-04-24 21:25 UTC, thxtomslf reviewed
Жирный лайк, так теперь круто в разделе друзей. Мне очень нравится. Ответь на вопросы пожалуйстааа

2023-04-24 21:25 UTC, thxtomslf commented on public/views/friendsView.js
> +		this._findFriendsBtn = document.getElementById('js-menu-find-friends');
Добавляем id для элементов, если надо точечно из js до него достучаться?

2023-04-24 21:25 UTC, thxtomslf commented on public/views/friendsView.js
>  	_addPagesListener() {
явно не хватает события, на которое надо загрузить новую пачку друзей (людей, подписчиков и тд)

2023-04-24 21:25 UTC, thxtomslf commented on public/stores/friendsStore.js
>          } else if (request.status === 401) {
было бы круто не алертить, если 500 прилетает, а показывать юзеру какое-нибудь окошко, что мол была ошибка. но тут скорее до**ываюсь

2023-04-24 21:27 UTC, thxtomslf commented
С батчами в разделе друзей надо все-таки доделать

2023-04-25 11:41 UTC, ArKarina commented on public/components/friend/friend.css
> +    cursor: pointer;
Что-то у меня его нет

2023-04-25 11:44 UTC, ArKarina commented on public/views/friendsView.js
> +		this._findFriendsBtn = document.getElementById('js-menu-find-friends');
да

2023-04-25 11:44 UTC, ArKarina commented on public/views/friendsView.js
>  	_addPagesListener() {
Видимо, скоро это как раз добавим

2023-04-25 11:45 UTC, ArKarina commented on public/stores/friendsStore.js
>          } else if (request.status === 401) {
Пока у нас нет формы для отрисовки этой ошибки

2023-04-25 13:17 UTC, BazaleevFedor approved these changes

2023-04-25 15:17 UTC, thxtomslf approved these changes

2023-04-25 17:54 UTC, DPeshkoff approved these changes

2023-04-25 17:54 UTC, merged