Cm 3.6 починить баги сообщений
frontend-park-mail-ru/2023_1_CashMap pull request #50
Opened 2023-04-26 17:15 UTC by BazaleevFedor

2023-04-26 22:04 UTC, DPeshkoff requested changes

2023-04-26 22:04 UTC, DPeshkoff commented on public/components/chat/chat.handlebars
> +        <div class="chat__header-image" style="visibility: hidden;"><img src="static/img/post_icons/post_menu.svg"></div>
Зачем?

2023-04-26 22:04 UTC, DPeshkoff commented on public/static/htmlConst.js
> +    logoTagline: 'Твоя социальная сеть 💩',
Что это?

2023-04-26 22:14 UTC, BazaleevFedor commented on public/components/chat/chat.handlebars
> +        <div class="chat__header-image" style="visibility: hidden;"><img src="static/img/post_icons/post_menu.svg"></div>
Настя сказала, что нужно убрать пока не реализовали функционал. Вынес в класс этот момент

2023-04-26 22:15 UTC, BazaleevFedor commented on public/static/htmlConst.js
> +    logoTagline: 'Твоя социальная сеть 💩',
Так. Тестировали отображение смайликов, забыл удалить(. Удалил

2023-04-27 15:18 UTC, DPeshkoff approved these changes

2023-04-30 20:21 UTC, merged